### PR TITLE
API.html

### PR DESCRIPTION
**Pull request by ThisisGenuine**

### CODE REVIEW

**Comment by OyePradumya** [comment]
It has been identified that your code lacks 6 dependencies.

The PR is being marked as incomplete. If the status doesn't change within 24 hours, the PR would be marked invalid.

**Review by ThisisGenuine — COMMENTED** [review]
I have created this new project by USING OpEN API

**Comment by ThisisGenuine** [comment]
brother please remove SPAM label.
Iam a beginner only so I dont know how to do this actually.
Brother SPAM lead to disqualified from fest.
please accept my apology and remove SPAM label.
Thanks brother in advanced.

**Comment by ThisisGenuine** [comment]
Please brother remove SPAM label
I dont know this kind of things
Iam New here.
Please remove SPAM label🙏

**Comment by ThisisGenuine** [comment]
Brother pls consider me 🙏

**Pull request closed without merging**
