### PR TITLE
added apply filter project

### PR DESCRIPTION
**Pull request by ditiya**
- [ ] Have you checked that there aren't other [projects](https://github.com/OyePradumya/Collection/) for the same topic in any language?
- [ ] Does your project contains a README and REQUIREMENTS file to help a newbie understand and execute your project code?
- [ ] Have you tested your code locally within another machine for it to execute without changes/updates?
- [ ] Does your code conform to the [hacktoberfest rules](https://hacktoberfest.com/participation)?
- [ ] Do you accept that this code is not available elsewhere on internet and you completely owe the rights to this project code.

-----

### CODE REVIEW

**Comment by ditiya** [comment]
added applying filter project

**Comment by OyePradumya** [comment]
The merging couldn't be done as there is no top level folder in which your project should reside in. Kindly add all the files in a single folder and upload the whole folder.

**Comment by ditiya** [comment]
please check the new commit

**Comment by OyePradumya** [comment]
Are devi ji add all the project files in a single folder.

**Pull request closed without merging**
